#######################
# Theme Customization #
#######################

title: NvzjuIr的博客                             # used in <title> tag & site header
author: NvzjuIr                        # used in a <meta> tag & /feed.xml
description: Hello 911 emergency, there's a handsome guy in my house!                         # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://nvzjuir.top              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/Nvzjuir/nvzjuir.github.io             # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: 首页
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: 项目
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: 关于我
    url: https://github.com/Nvzjuir/nvzjuir.github.io
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: 目录
    url: /posts.html
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Solana
    teaser: A responsive blog template written in Sass and vanilla JavaScript.
    url: https://github.com/rlue''            
    role: Creator
    category: Frontend Dev
  - title: Cortana
    teaser: A talking robot. Now available on Google Play?
    url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
    role: Core Team
    category: NLP
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: pretty

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
